linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
issues:
  max-per-linter: 0
  max-same-issues: 0
run:
  deadline: 5m
