sudo:     required
language: go
go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

# The "travis" build tag disables running tests in parallel.
# We this because Travis is slow (and sadly some of the tests
# tests must be timeout based).
env:
  - GOFLAGS='-tags=travis'

before_install: mkdir -p $GOPATH/bin
install:        make install
script:         make lint quick test
